// src/domain/errors/error-codes.ts

export const CodesError = {
  PUBLIC_ID_INVALID: "PUBLIC_ID_INVALID",
  PAGE_INVALID: "PAGE_INVALID",
  LIMIT_INVALID: "LIMIT_INVALID",

  FILE_ID_INVALID: "FILE_ID_INVALID",
  FILE_NAME_REQUIRED: "FILE_NAME_REQUIRED",
  FILE_PATH_REQUIRED: "FILE_PATH_REQUIRED",
  FILE_TYPE_ID_INVALID: "FILE_TYPE_ID_INVALID",
  FILE_SIZE_INVALID: "FILE_SIZE_INVALID",
  FILE_UPLOADED_BY_REQUIRED: "FILE_UPLOADED_BY_REQUIRED",

  TYPE_ID_INVALID: "TYPE_ID_INVALID",
  TYPE_NAME_REQUIRED: "TYPE_NAME_REQUIRED",
  TYPE_NAME_INVALID: "TYPE_NAME_INVALID",
  TYPE_FORMAT_INVALID: "TYPE_FORMAT_INVALID",
} as const;

export type CodesError = (typeof CodesError)[keyof typeof CodesError];
